/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControlBinario;
import controlador.ControlDecimal;
import controlador.ControlHexadecimal;
import controlador.ControlOctal;
import javax.swing.JOptionPane;

/**
 *
 * @author dpcq
 */
public class ConvertirNumeros extends javax.swing.JFrame {

    /**
     * Creates new form ConvertirNumeros
     */
    public ConvertirNumeros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        panelDec = new javax.swing.JPanel();
        lblIma1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDecimal = new javax.swing.JTextField();
        panelBin = new javax.swing.JPanel();
        lblIma2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBinario = new javax.swing.JTextField();
        panelOct = new javax.swing.JPanel();
        lblIma3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtOctal = new javax.swing.JTextField();
        panelHex = new javax.swing.JPanel();
        lblIma4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHexadecimal = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONVERSOR DE BASE");
        setPreferredSize(new java.awt.Dimension(650, 450));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese el número a convertir", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        panel1.setPreferredSize(new java.awt.Dimension(500, 400));
        panel1.setLayout(new java.awt.GridLayout(5, 2, 5, 5));

        panelDec.setBackground(new java.awt.Color(0, 0, 0));
        panelDec.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelDec.setLayout(new java.awt.BorderLayout());

        lblIma1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/dec.jpg"))); // NOI18N
        lblIma1.setPreferredSize(new java.awt.Dimension(80, 14));
        panelDec.add(lblIma1, java.awt.BorderLayout.LINE_START);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Decimal");
        panelDec.add(jLabel1, java.awt.BorderLayout.CENTER);

        panel1.add(panelDec);

        txtDecimal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtDecimal.setForeground(new java.awt.Color(0, 0, 204));
        txtDecimal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDecimal.setText("0");
        txtDecimal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDecimalFocusLost(evt);
            }
        });
        txtDecimal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDecimalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDecimalKeyTyped(evt);
            }
        });
        panel1.add(txtDecimal);

        panelBin.setBackground(new java.awt.Color(0, 0, 0));
        panelBin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBin.setLayout(new java.awt.BorderLayout());

        lblIma2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/bin.jpg"))); // NOI18N
        lblIma2.setPreferredSize(new java.awt.Dimension(80, 14));
        panelBin.add(lblIma2, java.awt.BorderLayout.LINE_START);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Binario");
        panelBin.add(jLabel5, java.awt.BorderLayout.CENTER);

        panel1.add(panelBin);

        txtBinario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtBinario.setForeground(new java.awt.Color(0, 0, 204));
        txtBinario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBinario.setText("0");
        txtBinario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBinarioFocusLost(evt);
            }
        });
        txtBinario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBinarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBinarioKeyTyped(evt);
            }
        });
        panel1.add(txtBinario);

        panelOct.setBackground(new java.awt.Color(0, 0, 0));
        panelOct.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelOct.setLayout(new java.awt.BorderLayout());

        lblIma3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/oct.jpg"))); // NOI18N
        lblIma3.setPreferredSize(new java.awt.Dimension(80, 14));
        panelOct.add(lblIma3, java.awt.BorderLayout.LINE_START);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Octal");
        panelOct.add(jLabel6, java.awt.BorderLayout.CENTER);

        panel1.add(panelOct);

        txtOctal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtOctal.setForeground(new java.awt.Color(0, 0, 204));
        txtOctal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOctal.setText("0");
        txtOctal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOctalFocusLost(evt);
            }
        });
        txtOctal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOctalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOctalKeyTyped(evt);
            }
        });
        panel1.add(txtOctal);

        panelHex.setBackground(new java.awt.Color(0, 0, 0));
        panelHex.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelHex.setLayout(new java.awt.BorderLayout());

        lblIma4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/hex.jpg"))); // NOI18N
        lblIma4.setPreferredSize(new java.awt.Dimension(80, 14));
        panelHex.add(lblIma4, java.awt.BorderLayout.LINE_START);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Hexadecimal");
        panelHex.add(jLabel7, java.awt.BorderLayout.CENTER);

        panel1.add(panelHex);

        txtHexadecimal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtHexadecimal.setForeground(new java.awt.Color(0, 0, 204));
        txtHexadecimal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHexadecimal.setText("0");
        txtHexadecimal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHexadecimalFocusLost(evt);
            }
        });
        txtHexadecimal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHexadecimalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHexadecimalKeyTyped(evt);
            }
        });
        panel1.add(txtHexadecimal);

        btnLimpiar.setBackground(new java.awt.Color(0, 255, 0));
        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        panel1.add(btnLimpiar);

        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panel1.add(btnSalir);

        getContentPane().add(panel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDecimalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDecimalKeyTyped
        char tecla = evt.getKeyChar();
        if ((tecla < '0' || tecla > '9') || (txtDecimal.getText().length() > 17)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDecimalKeyTyped

    private void txtBinarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBinarioKeyTyped
        char tecla = evt.getKeyChar();
        if ((tecla < '0' || tecla > '1') || (txtBinario.getText().length() > 62)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtBinarioKeyTyped

    private void txtOctalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOctalKeyTyped
        char tecla = evt.getKeyChar();
        if ((tecla < '0' || tecla > '7') || (txtOctal.getText().length() > 20)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtOctalKeyTyped

    private void txtHexadecimalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHexadecimalKeyTyped
        char tecla = evt.getKeyChar();
        if (((tecla < '0' || tecla > '9') && (tecla < 'A' || tecla > 'F') && (tecla < 'a' || tecla > 'f')) || (txtHexadecimal.getText().length() > 15)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtHexadecimalKeyTyped

    private void txtDecimalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDecimalKeyReleased
        ControlDecimal contDec = new ControlDecimal();
        String valor = txtDecimal.getText();
        if (!"".equals(valor)) {
            long nroDecimal = Long.parseLong(valor);
            txtBinario.setText(contDec.aBin(nroDecimal));
            txtOctal.setText(contDec.aOctal(nroDecimal));
            txtHexadecimal.setText(contDec.aHex(nroDecimal));
            if (valor.equals("0")) { //En caso que el texto sea 0 (Solo en el Hexadecimal)
                txtHexadecimal.setText("0");
            }
        }
    }//GEN-LAST:event_txtDecimalKeyReleased

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int opcion = JOptionPane.showConfirmDialog(panel1, "¿Está seguro de salir?", "Salir del Conversor de Base",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
        if (opcion == 0) {
            dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtBinarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBinarioKeyReleased
        ControlBinario contBin = new ControlBinario();
        String nroBinario = txtBinario.getText();
        if (!"".equals(nroBinario)) {
            txtDecimal.setText(String.valueOf(contBin.aDec(nroBinario)));
            txtOctal.setText(contBin.aOctal(nroBinario));
            txtHexadecimal.setText(contBin.aHex(nroBinario));
            if (nroBinario.equals("0")) { //En caso que el texto sea 0 (Solo en el Hexadecimal)
                txtHexadecimal.setText("0");
            }
        }
    }//GEN-LAST:event_txtBinarioKeyReleased

    private void txtOctalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOctalKeyReleased
        ControlOctal contOct = new ControlOctal();
        String nroOctal = txtOctal.getText();
        if (!"".equals(nroOctal)) {
            txtDecimal.setText(String.valueOf(contOct.aDec(nroOctal)));
            txtBinario.setText(contOct.aBin(nroOctal));
            txtHexadecimal.setText(contOct.aHex(nroOctal));
            if (nroOctal.equals("0")) { //En caso que el texto sea 0 (Solo en el Hexadecimal)
                txtHexadecimal.setText("0");
            }
        }
    }//GEN-LAST:event_txtOctalKeyReleased

    private void txtHexadecimalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHexadecimalKeyReleased
        ControlHexadecimal contHexa = new ControlHexadecimal();
        String numHex = txtHexadecimal.getText();
        if (!"".equals(numHex)) {
            String nroHexadecimal = txtHexadecimal.getText();
            txtDecimal.setText(String.valueOf(contHexa.aDec(nroHexadecimal)));
            txtBinario.setText(contHexa.aBin(nroHexadecimal));
            txtOctal.setText(contHexa.aOct(nroHexadecimal));
        }
    }//GEN-LAST:event_txtHexadecimalKeyReleased

    private void txtDecimalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDecimalFocusLost
        if ("".equals(txtDecimal.getText())) {
            txtDecimal.setText("0");
        }
    }//GEN-LAST:event_txtDecimalFocusLost

    private void txtBinarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBinarioFocusLost
        if ("".equals(txtBinario.getText())) {
            txtBinario.setText("0");
        }
    }//GEN-LAST:event_txtBinarioFocusLost

    private void txtOctalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOctalFocusLost
        if ("".equals(txtOctal.getText())) {
            txtOctal.setText("0");
        }
    }//GEN-LAST:event_txtOctalFocusLost

    private void txtHexadecimalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHexadecimalFocusLost
        if ("".equals(txtHexadecimal.getText())) {
            txtHexadecimal.setText("0");
        }
    }//GEN-LAST:event_txtHexadecimalFocusLost

    public void limpiarCampos() {
        txtDecimal.setText("0");
        txtBinario.setText("0");
        txtOctal.setText("0");
        txtHexadecimal.setText("0");
    }

    public void control0Hex(String texto) {
        if (!texto.equals("0")) { //Si no escribimos 0
            txtHexadecimal.setText(texto);
        } else { //En caso de escribir 0
            txtHexadecimal.setText("0");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConvertirNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConvertirNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConvertirNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConvertirNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvertirNumeros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblIma1;
    private javax.swing.JLabel lblIma2;
    private javax.swing.JLabel lblIma3;
    private javax.swing.JLabel lblIma4;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panelBin;
    private javax.swing.JPanel panelDec;
    private javax.swing.JPanel panelHex;
    private javax.swing.JPanel panelOct;
    private javax.swing.JTextField txtBinario;
    private javax.swing.JTextField txtDecimal;
    private javax.swing.JTextField txtHexadecimal;
    private javax.swing.JTextField txtOctal;
    // End of variables declaration//GEN-END:variables
}
